---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: r_instances

- name: Debug instances 
  debug:
    msg: "Server is {{ __instance.name }}"
    verbosity: 2
  loop: "{{ r_instances.results }}"
  loop_control:
    loop_var: __instance

# - name: Delete instances
#   os_server:
#     cloud: openstack
#     server: "{{ __instance.name }}"
#     state: absent
#     wait: true
#     timeout: 180
#   loop: "{{ r_instances.results }}"
#   loop_control:
#     loop_var: __instance
  
