---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: results

- name: save the Json data to a Variable as a Fact
  set_fact:
    jsondata: "{{ results | from_json }}"

- name: Server Names
  set_fact:  
    servernames:  "{{ jsondata | json_query(jmesquery) }}"
  vars:
    jmesquery: "openstack_servers[*].name"

- name: Print all server names
  debug: 
    msg: "{{ item }}"
  with_items: 
    - "{{ servernames }}"

# - name: Debug instances2 
#   debug:
#     msg: "Server is {{ __instance.openstack_servers.name }}"
#     verbosity: 2
#   loop: "{{ results }}"
#   loop_control:
#     loop_var: __instance

# - name: Delete instances
#   os_server:
#     cloud: openstack
#     server: "{{ __instance.name }}"
#     state: absent
#     wait: true
#     timeout: 180
#   loop: "{{ results }}"
#   loop_control:
#     loop_var: __instance
  
