---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: results

- name: Debug instances 
  debug:
    msg: "{{ results }}"

- name: Debug instances2 
  debug:
    msg: "Server is {{ __instance.__openstack_server.name }}"
    verbosity: 2
  loop: "{{ results }}"
  loop_control:
    loop_var: __instance

# - name: Delete instances
#   os_server:
#     cloud: openstack
#     server: "{{ __instance.name }}"
#     state: absent
#     wait: true
#     timeout: 180
#   loop: "{{ results }}"
#   loop_control:
#     loop_var: __instance
  
