
- name: Delete OpenStack Servers
  hosts: localhost
  gather_facts: false
  vars:
    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
    OPENTLC_ID: "{{ lookup('env','OPENTLC_ID') }}"
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{ OSP_GUID }}.{{ OSP_DOMAIN }}"
       group: workstation
       ansible_user: cloud-user
       ansible_ssh_private_key_file: "/root/.ssh/openstack.pem"

- name: Delete OpenStack Servers
  hosts: workstation
  gather_facts: false
  become: true
  roles:
    - osp-instance-delete