
- hosts: localhost
  vars:
    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
    OPENTLC_ID: "{{ lookup('env','OPENTLC_ID') }}"
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{ OSP_GUID }}.{{ OSP_DOMAIN }}"
       group: workstation
       ansible_user: "{{ OPENTLC_ID }}"
       ansible_ssh_private_key_file: "~/.ssh/mykey.pem"

- hosts: workstation
  become: yes
  roles:
   - osp-servers
