
# tasks file for osp-facts
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: r_os_servers

- name: Add host to in memory inventory
  add_host:
    name: "{{ item.public_v4 }}"
    group:
      - "{{ item.metadata.group }}"
      - "{{ item.metadata.deployment_name }}"
  loop: "{{ r_os_servers.openstack_servers }}"

- name: Check host is in the in memory inventory
  debug:
    msg: "{{ item }}"
  with_inventory_hostnames:
    - all

