---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  yum_repository:
    name: Internal_Repo
    description: Internal_Repo
    baseurl: https://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
    gpgcheck: no

- name: install base tools and packages
  package:
    name: "{{ __package }}"
    state: present
  loop: "{{ yum_packages }}"        
  loop_control:
    loop_var: __package

